version: "3.8"

services:
  txdx:
    container_name: txdx
    build: ./
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    command: yarn start
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13.0-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
